module.exports = {
  env: {
    node: true,
  },
  extends: ['plugin:node/recommended', 'plugin:security/recommended'],
  plugins: ['node', 'security'],
  rules: {
    'node/exports-style': ['error', 'module.exports'],
    'node/prefer-global/buffer': ['error', 'always'],
    'node/prefer-global/console': ['error', 'always'],
    'node/prefer-global/process': ['error', 'always'],
    'node/prefer-global/url': ['error', 'always'],
    'node/prefer-global/url-search-params': ['error', 'always'],
    'node/prefer-global/text-encoder': ['error', 'always'],
    'node/prefer-global/text-decoder': ['error', 'always'],
    'node/no-unpublished-require': 'error',
    'node/no-unpublished-import': 'error',
    'node/no-extraneous-require': 'error',
    'node/no-extraneous-import': 'error',
    'node/no-deprecated-api': 'error',
    'node/shebang': 'warn',
    'node/callback-return': 'error',
    'node/file-extension-in-import': ['error'],
    'node/global-require': 'warn',
    'node/handle-callback-err': 'error',
    'node/no-callback-literal': 'error',
    'node/no-mixed-requires': 'error',
    'node/no-new-require': 'error',
    'node/no-path-concat': 'error',
    'node/no-process-env': 'off',
    'node/no-process-exit': 'error',
    'node/no-restricted-import': ['error', []],
    'node/no-restricted-require': ['error', []],
    'node/no-sync': 'warn',
    'node/prefer-promises/dns': 'warn',
    'node/prefer-promises/fs': 'warn',
    'node/no-unsupported-features/es-syntax': 'error',
    'node/no-unsupported-features/es-builtins': 'error',
  },
};
