module.exports = {
  extends: [
    'plugin:unicorn/recommended',
    'plugin:prettier/recommended',
    'prettier/unicorn',
  ],
  plugins: ['unicorn', 'prettier'],
  rules: {
    'prettier/prettier': [
      'error',
      {
        bracketSpacing: true,
        jsxBracketSameLine: false,
        singleQuote: true,
        jsxSingleQuote: true,
        trailingComma: 'all',
        useTabs: false,
        tabWidth: 2,
        semi: true,
        quoteProps: 'as-needed',
        arrowParens: 'avoid',
        proseWrap: 'preserve',
        htmlWhitespaceSensitivity: 'css',
        vueIndentScriptAndStyle: true,
        endOfLine: 'auto',
        printWidth: 80,
      },
    ],
    'unicorn/filename-case': ['error', { case: 'kebabCase' }],
    'unicorn/no-abusive-eslint-disable': 'error',
    'unicorn/catch-error-name': 'error',
    'prefer-exponentiation-operator': 'error',
    'unicorn/prefer-exponentiation-operator': 'off',
    'unicorn/better-regex': 'error',
    'unicorn/regex-shorthand': 'off',
    curly: ['error', 'multi'],
    'array-bracket-even-spacing': 'off',
    'computed-property-even-spacing': 'off',
    'object-curly-even-spacing': 'off',
  },
};
